# Generated by Django 4.1.7 on 2023-03-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('hospital_city', models.CharField(max_length=100)),
                ('hospital_distance', models.CharField(max_length=50)),
                ('hospital_rating', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
