# Generated by Django 4.1.7 on 2023-03-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_images',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
