# Generated by Django 4.1.7 on 2023-04-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hospital_hospital_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_location',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_images',
            field=models.ImageField(upload_to='ambulancetrackerproject/'),
        ),
    ]
