# Generated by Django 4.1.7 on 2023-04-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ambulance_alter_hospital_hospital_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='ambulance_time',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
